# Generated by Django 4.2.1 on 2023-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('picture', models.ImageField(default='', upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('joined', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'öğrenci',
                'verbose_name_plural': 'öğrenciler',
                'ordering': ['first_name'],
            },
        ),
    ]
