# Generated by Django 4.2.1 on 2023-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, choices=[(10, 'yaş: 10'), (20, 'yaş: 20'), (30, 'yaş: 30'), (40, 'yaş: 40')], default=0, null=True),
        ),
    ]
