# Generated by Django 4.2.1 on 2023-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0004_alter_customer_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-age'], 'verbose_name': 'Müşteri', 'verbose_name_plural': 'Müşteriler'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'yaş: 0'), (10, 'yaş: 10'), (20, 'yaş: 20'), (30, 'yaş: 30'), (40, 'yaş: 40')], default=0, null=True),
        ),
    ]
